### ISSUE TITLE
fix example in IMDB dataset docs

### ISSUE THREAD

**Issue by lukasnalezenec** [keras-team/keras-io#1036]
Last example contains line
" ".join(inverted_word_index.get[i] for i in x_train[0])
But it is wrong it have to be 
" ".join(inverted_word_index.get(i - 3, "?") for i in x_train[0])
Since first indexed are reserved.

**Comment by SuryanarayanaY** [comment]
Hi @lukasnalezenec ,

The original code in tutorial is correct. With the code change you proposed the decoded sequence will become unordered.
You can check the result in the attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/02a28474403f8ff6a2843d11ca51ad4d/keras_io-1036.ipynb). The reason is that here each word token have an index which is not sorted in order.

Thank you!
