### ISSUE TITLE
A 'NoneType' error occured from 'timeseries_traffic_forecasting.py'

### ISSUE THREAD

**Issue by tigflanker** [keras-team/keras-io#1106]
https://github.com/keras-team/keras-io/blob/2da9acbb1f0e6522f41753d23a4211d35f4976cb/examples/timeseries/timeseries_traffic_forecasting.py#L571

@akhodadadi
Hi, There is a 'NoneType' error occured when i try to rerun 'timeseries_traffic_forecasting.py'.
As follow code run, gcn_out has assign to None.
'''
        ... ...
        inputs = tf.transpose(inputs, [2, 0, 1, 3])

        gcn_out = self.graph_conv(inputs)
'''

**Comment by akhodadadi** [comment]
@ tigflanker 
Hi, I can't replicate the error. I can run the code successfully. could you provide more context? are you trying to rerun the script as is or you are making some changes?

**Comment by tigflanker** [comment]
Hi akhodadadi, thank you for reply. To ensure we have the same rerun environment. I rerun the code on kaggle site with new notebook.
Pls check the attach here: 
[timeseries_traffic_forecasting.zip](https://github.com/keras-team/keras-io/files/9848114/timeseries_traffic_forecasting.zip)
![20221024093811](https://user-images.githubusercontent.com/22868157/197431047-a013a490-40a2-4932-9abe-25514ae8019d.png)

**Comment by akhodadadi** [comment]
@tigflanker I can run the notebook as well with no error. Could you create a conda env with python 3.8:

`conda create -n python=3.8`

and install the following requirements in it using pip?

pandas==1.5.1
tensorflow==2.10.0
matplotlib==3.6.1

**Comment by SuryanarayanaY** [comment]
Hi @tigflanker ,

I have tested the tutorial and its executing fine in multiple runs also. Myself executed the tutorial two times and its working normal. Please refer to attached gist for [run-1](https://colab.sandbox.google.com/gist/SuryanarayanaY/4957a26663f66aaef0414db22eea6cf8/kerasio_1106-gpu-timeseries_traffic_forecasting.ipynb) and [run-2](https://colab.sandbox.google.com/gist/SuryanarayanaY/9b99472d3d638659ca261a5ccd595db8/kerasio_1106-gpu-timeseries_traffic_forecasting-run-2.ipynb).

The problem seems with your local environment. Could you please let us know if this is still an issue for you? Thanks!
