### ISSUE TITLE
If a RNN is stateful, it needs to know its batch size. Specify the batch size of your input tensors:

### ISSUE THREAD

**Issue by sz97z** [keras-team/keras-io#1122]
I am using API to build the SimpleRNN network model. Then I ran into a problem, if I use shape in keras.input to determine the input size, I run into this problem
![pycharm64_NmzdWqVXD0](https://user-images.githubusercontent.com/49617050/198182276-d6f24ba4-1dc5-4a61-af14-bd58ec55a2e1.png)
my code is 
![pycharm64_KaSzjLMPt5](https://user-images.githubusercontent.com/49617050/198182352-3f00cfcc-6de0-4644-8e3f-68c80e56acbf.png)
If I use batch_shape to determine the input size, there is a problem at model.fit
![pycharm64_8DxsR8Grnq](https://user-images.githubusercontent.com/49617050/198182819-6b0f0ab2-ec9b-4634-bbf1-eaad27398670.png)
my model.fit is
![pycharm64_tHTbXqzlQN](https://user-images.githubusercontent.com/49617050/198182903-de686ef1-30a8-450c-ab41-86d6ff98de59.png)
my new code is 
![pycharm64_DxRd7BwCnl](https://user-images.githubusercontent.com/49617050/198182946-b0979b13-52ea-4641-a8e6-8002da254a84.png)

tensorflow2.0.0   kears2.6.0

**Comment by SuryanarayanaY** [comment]
Hi @sz97z ,

The problem may be due to the argument `y` passed to `model.fit` . As per [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit:~:text=for%20x.-,y,not%20be%20specified%20(since%20targets%20will%20be%20obtained%20from%20x).,-batch_size) the argument `y` supports numpy arrays or TF tensors. But `dict` is being passed to `y` which might be creating ambiguity.

You can pass both inputs and outputs as tf.data.Dataset object in which case there should not pass anything to argument '`y`' in `model.fit()`.

Providing more details or a minimal code snippet can help us to resolve the problem.
