### ISSUE TITLE
Wrong parameter to MultiHeadAttention in example image_classification_with_vision_transformer

### ISSUE THREAD

**Issue by hubtub2** [keras-team/keras-io#1184]
In /examples/vision/image_classification_with_vision_transformer.py 

Shouldn't the `key_dim` parameter to `MultiHeadAttention()` be `projection_dim / num_head` instead of  `projection_dim`?

**Comment by SuryanarayanaY** [comment]
Hi @hubtub2 ,

`key_dim` parameter represent size of each attention head for `query` and `key`. If you keep it higher the parameters/weights will increase and for lower value the no of parameters will decrease. 

It won't have any effect on Output tensor shape since  attention_output is the result of the computation, of shape (B, T, E), where T is for target sequence shapes and E is the query input last dimension if output_shape is None. Otherwise, the multi-head outputs are projected to the shape specified by `output_shape`.

You can try with both `key_dim = projection_dim // num_head` and `key_dim = projection_dim` and both will execute without any problem.
