### ISSUE TITLE
I think there is an error on the Timeseries forecasting for weather  code.

### ISSUE THREAD

**Issue by skanskan** [keras-team/keras-io#1208]
Hello.

I've been following the "Timeseries forecasting for weather prediction" code found here:
https://keras.io/examples/timeseries/timeseries_weather_forecasting/

I think there is an error in this code

```
for x, y in dataset_val.take(5):
    show_plot(
        [x[0][:, 1].numpy(), y[0].numpy(), model.predict(x)[0]],
        12,
        "Single Step Prediction",
    )
```

Why is that **12** a fixed number there?
Shouldn't it be a parameter changing at every step?

**Comment by SuryanarayanaY** [comment]
Hi @skanskan ,

Please find this note in the tutorial.

> We are tracking data from past 720 timestamps (720/6=120 hours). This data will be used to predict the temperature after 72 timestamps (72/6=12 hours).

Here we are using previous 720 timesteps data to predict the output at future 72nd time step.Each time step is of 10 seconds but we are taking single data point for each hour to reduce the size of input array as there is no much variation in data hourly. We did this via the `sampling_rate` argument in `timeseries_dataset_from_array` utility where each data point is hourly now.

Hence the 72nd time step in Future becomes 72/6 = 12 hours now. We can store this in a variable though and pass it instead of hard coded. But we need to keep in mind that here the data preprocessing done in a such a way that we have taken 720 timesteps data ( 120 hours of data) to predict the 72nd time step(12th hour) data in Future.

If you want to change this value from 12 you need to preprocess the data accordingly.

You can change this value to 6 the value of model.predict still predicts value at time step 12 but plots the prediction at 6th time step since it has no role in model.predict.

Please find the attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/5b655844d2ae09b28fd8ab3d4d2a6d8a/kerasio_1208-timeseries_weather_forecasting.ipynb) for checking the same. Thanks!
