### ISSUE TITLE
dataset url of pointnet_segmentation.py is broken

### ISSUE THREAD

**Issue by mathijs95** [keras-team/keras-io#1317]
dataset_url = "https://git.io/JiY4i" is broken.
Could you please update the link?

If I go to the link I get Internal Server Error

![image](https://user-images.githubusercontent.com/57390539/229757612-60778688-ec6e-4458-8cff-c4203ed1ccf5.png)

**Comment by mathijs95** [comment]
I found the dataset via https://archive.org/web so I can proceed :-)

**Comment by sachinprasadhs** [comment]
Could you please close the issue if there is no action to be taken from our side. Thanks!

**Comment by sachinprasadhs** [comment]
I got the tutorial which you are talking about, 
@sayakpaul Could you please look into this, since the tutorial which you have authored uses git.io link, which is no longer available.
https://github.com/keras-team/keras-io/blob/8f49b3ec63c7d959b9457ab7cc961ce4ca922d2f/examples/vision/ipynb/pointnet_segmentation.ipynb#L103

Alternative source of dataset could be found in Tensorflow datasets here https://www.tensorflow.org/graphics/api_docs/python/tfg/datasets/shapenet/Shapenet

**Comment by sachinprasadhs** [comment]
https://git.io/JiY4i is now working and the tutorial is migrated to Keras 3, please find the latest tutorial here https://keras.io/examples/vision/pointnet_segmentation/
