### ISSUE TITLE
Possible memory leak in Point cloud classification with PointNet example

### ISSUE THREAD

**Issue by jldk20** [keras-team/keras-io#186]
line 266 test_dataset.take(1) is processing infinitely while allocating 64GB of memory + approx. 130GB of swap. I stopped the script after ~1 hour. Any ideas what might be causing this issues/ any suggestion how to handle it? By the way: I'm using tensorflow 1.14/keras 2.2.4 

Host computation capabilities:
i9 16 cores @4.2GHz
64GB Ram
2x 2080Ti's + NvLink Bridge
Windows 10 (same issue on Ubuntu 16.04)

**Comment by sachinprasadhs** [comment]
Hi,

Thanks for reporting the issue.

It is always suggested to use same matching `TensorFlow` and `Keras` version.

Since we no longer support Tensorflow 1.x, it is recommended to use latest version.

You can use Keras using Tensorflow import as below.

```
import tensorflow as tf
input_layer = tf.keras.Input(shape=[100])
```

Let us know if you still face any error in latest version. Thanks!
