### ISSUE TITLE
tutorial bug in consistency_training 

### ISSUE THREAD

**Issue by 0x1orz** [keras-team/keras-io#1864]
### Issue Type

Documentation Bug

### Source

source

### Keras Version

keras 2

### Custom Code

Yes

### Current Behavior?

A bug happened!

examples/vision/consistency_training.py in google [colab](https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/vision/ipynb/consistency_training.ipynb#scrollTo=vis6pLvU4jAc)

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-5-b3c40fb357b7>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from official.vision.image_classification.augment import RandAugment
      2 from tensorflow.keras import layers
      3 
      4 import tensorflow as tf
      5 import tensorflow_addons as tfa

ModuleNotFoundError: No module named 'official.vision.image_classification'

### Standalone code to reproduce the issue or tutorial link

```shell
https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/vision/ipynb/consistency_training.ipynb#scrollTo=vis6pLvU4jAc
```

**Comment by chunduriv** [comment]
@0x1orz,

I would like to suggest using the following import statement:

`from official.vision.ops.augment import RandAugment`

instead of this one:

`from official.vision.image_classification.augment import RandAugment`

This change will make your code more consistent with the [models.official.vision](https://github.com/tensorflow/models/blob/master/official/vision/ops/augment.py#L2360)
