### ISSUE TITLE
Save Transformer model

### ISSUE THREAD

**Issue by arijit32** [keras-team/keras-io#276]
https://github.com/keras-team/keras-io/blob/master/examples/nlp/text_classification_with_transformer.py

Can someone tell me how to save the model here? I am having some trouble saving any model with this architecture

**Comment by efacco** [comment]
Hello, anyone replying to this? I am trying to save checkpoints but I keep getting an error related to the input shape. Thank you

**Comment by SuryanarayanaY** [comment]
Hi @arijit32 ,

This issue seems resolved. I can able to save and reload model using `model.save()` for saving and `tf.keras.models.load_model()` API for reloading. U have tested the same tutorial you mentioned and you can find the same in attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/31a84d441f11864870182526a1f159f2/keras_io-276-text_classification_with_transformer.ipynb#scrollTo=pyNLaB6Jk5aQ).

Please check the gist and confirm. Please feel free to close the issue if you find resolved. If having any other issue let us know.

Thanks!
