### ISSUE TITLE
Why is num_classes is 3 in oxford_pets_image_segmentation.py

### ISSUE THREAD

**Issue by chenaaan** [keras-team/keras-io#315]

**Comment by sachinprasadhs** [comment]
Hi, 

Thanks for reporting the issue.

Since the issue which you are referring to is Segmentation issue here https://keras.io/examples/vision/oxford_pets_image_segmentation/.

Consider the below prediction for the image
![image](https://github.com/keras-team/keras-io/assets/73069040/5c1c8e1f-8c6a-4c26-844f-ca407421e550)

For Image segmentation the number of classes 3 refers to.
1. Background (Grey area)
2. Outline (White area) 
3. Inner Object (Black area)
