### ISSUE TITLE
Style Transfer : Cannot convert value None to a TensorFlow DType

### ISSUE THREAD

**Issue by oprilium** [keras-team/keras-io#358]
Hello,
I am quite new to deep learning with Keras. Already have tried it with some success for image classification and style transfer, though using the R interface (using Rstudio). Recently I have been trying to do the same tasks, but "directly" in python (I use Rstudio, Reticulate).

I tried to run this code ipsis verbis https://github.com/keras-team/keras-io/blob/master/examples/generative/neural_style_transfer.py, all seems to be ok, but in the end when I run the optimizer I get this error message:  

`TypeError: Cannot convert value None to a TensorFlow DType.`

tensorflow version is 2.2.0
keras version is 2.3.0

Thanks

**Comment by SuryanarayanaY** [comment]
Hi @oprilium ,

I have tested the tutorial with TF 2.12 versions and there is no such error now though I am not sure whether it is due to your own environment or with TF2.2V. Please refer to attached colab [gist](https://colab.research.google.com/gist/SuryanarayanaY/72d69247edde3f33ddb106b677f6e65f/keras-io-358-neural_style_transfer.ipynb) which works fine now.

Please cross check and confirm whether we are good to mark the issue as resolved. Thanks!
