### ISSUE TITLE
Error in "semantic_similarity_with_bert.py"

### ISSUE THREAD

**Issue by ReySadeghi** [keras-team/keras-io#360]
Hi, 
when I run "semantic_similarity_with_bert.py" on google-colab, I got this error:

TypeError                                 Traceback (most recent call last)
<ipython-input-12-46653d782cd7> in <module>()
     26     bi_lstm = tf.keras.layers.Bidirectional(
     27         tf.keras.layers.LSTM(64, return_sequences=True)
---> 28     )(sequence_output)
     29     # Applying hybrid pooling approach to bi_lstm sequence output.
     30     avg_pool = tf.keras.layers.GlobalAveragePooling1D()(bi_lstm)

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/input_spec.py in assert_input_compatibility(input_spec, inputs, layer_name)
    199     # have a `shape` attribute.
    200     if not hasattr(x, 'shape'):
--> 201       raise TypeError('Inputs to a layer should be tensors. Got: %s' % (x,))
    202 
    203   if len(inputs) != len(input_spec):

TypeError: Inputs to a layer should be tensors. Got: last_hidden_state

**Comment by MohamadMerchant** [comment]
Hi, 

The error is due to some new changes in the huggingface transformers version. Please try running it with version=2.11.0 and it will not show the error.
!pip install transformers==2.11.0

Thanks.

**Comment by Jyotirmoy-s** [comment]
already installed !pip install transformers==2.11.0 but still it shows the following error
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.
WARNING:tensorflow:The parameters `output_attentions`, `output_hidden_states` and `use_cache` cannot be updated when calling a model.They have to be set to True/False in the config object (i.e.: `config=XConfig.from_pretrained('name', output_attentions=True)`).
WARNING:tensorflow:The parameter `return_dict` cannot be set in graph mode and will always be set to `True`.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-46653d782cd7> in <module>()
     26     bi_lstm = tf.keras.layers.Bidirectional(
     27         tf.keras.layers.LSTM(64, return_sequences=True)
---> 28     )(sequence_output)
     29     # Applying hybrid pooling approach to bi_lstm sequence output.
     30     avg_pool = tf.keras.layers.GlobalAveragePooling1D()(bi_lstm)

2 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/wrappers.py in __call__(self, inputs, initial_state, constants, **kwargs)
    537 
    538     if initial_state is None and constants is None:
--> 539       return super(Bidirectional, self).__call__(inputs, **kwargs)
    540 
    541     # Applies the same workaround as in `RNN.__call__`

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    996         inputs = self._maybe_cast_inputs(inputs, input_list)
    997 
--> 998       input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    999       if eager:
   1000         call_fn = self.call

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/input_spec.py in assert_input_compatibility(input_spec, inputs, layer_name)
    199     # have a `shape` attribute.
    200     if not hasattr(x, 'shape'):
--> 201       raise TypeError('Inputs to a layer should be tensors. Got: %s' % (x,))
    202 
    203   if len(inputs) != len(input_spec):

TypeError: Inputs to a layer should be tensors. Got: last_hidden_state

**Comment by yucongo** [comment]
Still doesn't seem to work with transformers==2.11.0:  the same error

**Comment by iamlockelightning** [comment]
@MohamadMerchant Hi, can I know how to solve this problem entirely with the latest version of transformers instead of a downgrade of it? (Since the latest transformers is 4.x.x now.)

**Comment by iamlockelightning** [comment]
> @MohamadMerchant Hi, can I know how to solve this problem entirely with the latest version of transformers instead of a downgrade of it? (Since the latest transformers is 4.x.x now.)

solved by:


```
bert_output = bert_model(
    input_ids, attention_mask=attention_masks, token_type_ids=token_type_ids
)
sequence_output = bert_output.last_hidden_state
pooled_output = bert_output.pooler_output
```

Thanks anyway~

**Comment by giangdip2410** [comment]
@iamlockelightning : thank you for your solution. After changing as your code, I face another issue : 

File "predict.py", line 19, in predict
    model.load_weights(filepath="best_bert2.hdf5")
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 2234, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 710, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/backend.py", line 3706, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype(x)))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/values.py", line 782, in assign
    self, value, use_locking=use_locking, name=name, read_value=read_value)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/values_util.py", line 145, in on_write_assign
    read_value=read_value)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/values.py", line 940, in _update
    return self._update_cross_replica(update_fn, value, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/values.py", line 894, in _update_cross_replica
    self, update_fn, args=(value,), kwargs=kwargs, group=True)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 2494, in update
    return self._update(var, fn, args, kwargs, group)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/mirrored_strategy.py", line 711, in _update
    **distribute_utils.select_replica_mirrored(i, kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 572, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/values_util.py", line 139, in <lambda>
    assign_fn = lambda var, *a, **kw: var.assign(*a, **kw)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 891, in assign
    (tensor_name, self._shape, value_tensor.shape))
ValueError: Cannot assign to variable tf_bert_model/bert/encoder/layer_._0/attention/self/query/kernel:0 due to variable shape (768, 12, 64) and value shape (768, 768) are incompatible

Do you have any idea for this issue ? thank you.

**Comment by sachinprasadhs** [comment]
Hi, 

Could you please refer the fix mentioned here https://github.com/keras-team/keras-io/pull/718/commits/be29d23d41e8f709a1ae88c6a316045baaaa84c8 and close the issue. Thanks!
