### ISSUE TITLE
movielens recommendations transformers example broken

### ISSUE THREAD

**Issue by ddofer** [keras-team/keras-io#376]
The notebook/code/colab is broken for the example "[A Transformer-based recommendation system](https://keras.io/examples/structured_data/movielens_recommendations_transformers/)": 
The [ipynb ](https://github.com/keras-team/keras-io/blob/master/examples/structured_data/ipynb/movielens_recommendations_transformers.ipynb)fails to load: 
https://github.com/keras-team/keras-io/blob/master/examples/structured_data/ipynb/movielens_recommendations_transformers.ipynb

[Colab ](https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/structured_data/ipynb/movielens_recommendations_transformers.ipynb)is also broken, with the following error: 
> 
> There was an error loading this notebook. Ensure that the file is accessible and try again.
> **Unexpected token ] in JSON at position 25830**
> 
> https://github.com/keras-team/keras-io/blob/master/examples/structured_data/ipynb/movielens_recommendations_transformers.ipynb
> Unexpected token ] in JSON at position 25830
> SyntaxError: Unexpected token ] in JSON at position 25830
>     at JSON.parse (<anonymous>)
>     at Ca.program_ (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20210212-080411-RC00_357173882:1374:452)
>     at Ea (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20210212-080411-RC00_357173882:19:336)
>     at Ca.next_ (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20210212-080411-RC00_357173882:17:503)
>     at Ga.next (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20210212-080411-RC00_357173882:20:206)
>     at f (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20210212-080411-RC00_357173882:62:101)

**Comment by SuryanarayanaY** [comment]
Hi @ddofer ,

We are going through backlogs and this issue is not persistent now.

I have tested the tutorial and I got encoding related error at below code.

I have also raised a PR #1406  for this which is under review now.

If we change the encoding and executing the code then everything working fine. Please refer attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/1e2a7ce6ff89abaf7c53a567ec8ac80a/kerasio_376-movielens_recommendations_transformers.ipynb). The reported error by you no more exists now.

Please cross check and confirm whether is it good to close this issue now. Thanks!
