### ISSUE TITLE
where to go to fix this 

### ISSUE THREAD

**Issue by epsilon-deltta** [keras-team/keras-io#419]
https://keras.io/api/callbacks/model_checkpoint/
in this url , i wanna change something so could you give me the repository url for pull request
thankyou😁😁😁😁

**Comment by SuryanarayanaY** [comment]
Hi @epsilon-deltta ,

It seems all these pages are auto generated from internal scripts. It seems for all the callback classes in callbacks module the source link exists but not opening. I will bring this to Doc team attention. Either we may need to remove the source link if the document is auto generated through some internal script or we need to provide URL link for same.I will let you know.

Meanwhile can you share which details you want to modify for what reason?

Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @epsilon-deltta ,

Now the source link is working and you can click on it to move to the source code [here](https://github.com/keras-team/keras/blob/v2.13.1/keras/callbacks.py#L1224). 

If you still have something to work here please feel free to do so or confirm us so that we can have a look into the proposed changes. Thanks!
