### ISSUE TITLE
Please add pip3 install tensorflow_addons to the list of commands in the colab example for CycleGAN

### ISSUE THREAD

**Issue by shyamalschandra** [keras-team/keras-io#423]
https://github.com/keras-team/keras-io/blob/master/examples/generative/cyclegan.py

Please add that command prior to the first command.  I don't have commit privileges.

**Comment by SuryanarayanaY** [comment]
Hi @shyamalschandra ,

Thanks for reaching us. The tutorials may not have installation commands for regular packages.Since Colab environment already have installations tensorflow, numpy, matplotlib etc there is no need of installation commands of these packages.If you download this file for your local environment then you need to ensure installation of all packages any way. 

IMO the installation commands were excluded and left it to users.

I think user can install the `tensorflow_addons` as the log message is very clear. Still if you feel that this command also needed in the tutorial please feel free to raise a PR.

Thanks!

Thanks!
