### ISSUE TITLE
Why add 1 for max_features in Embedding layer?

### ISSUE THREAD

**Issue by JifuZhao** [keras-team/keras-io#424]
https://github.com/keras-team/keras-io/blob/77d1d9a82d26652f3afcc24dbab3115fecffd62a/examples/nlp/text_classification_from_scratch.py#L200

```python
text_input = tf.keras.Input(shape=(1,), dtype=tf.string, name='text')
x = vectorize_layer(text_input)
x = layers.Embedding(max_features + 1, embedding_dim)(x)
```

**Comment by SuryanarayanaY** [comment]
Hi @JifuZhao ,

The first positional argument (`input_dim`) of Embedding layer should be:

> Integer. Size of the vocabulary, i.e. maximum integer index + 1.

We need to do +1 only if the max_features is actually maximum integer index, since indexing starts from '0'. For this case it is  not needed and in actual model this code not used as you can see it here. 

https://github.com/keras-team/keras-io/blob/77d1d9a82d26652f3afcc24dbab3115fecffd62a/examples/nlp/text_classification_from_scratch.py#L248

The reported line of code is used in text block and hence no affect in the actual code block. We will discuss and if required changes will be done appropriately to avoid confusion.

Thanks!
