### ISSUE TITLE
Classification with Neural Decision Forests

### ISSUE THREAD

**Issue by Lpourchot** [keras-team/keras-io#470]
https://keras.io/examples/structured_data/deep_neural_decision_forests/

def encode_inputs(inputs):
vocabulary_size should be replaced by vocab_size

**Comment by SuryanarayanaY** [comment]
Hi @Lpourchot ,

I am assuming you are referring to the `vocab_size()` and `vocabulary_size()` of the `StringLookup` layer class has built in methods `vocab_size()` and `vocabulary_size()` and both are same.Now `vocab_size()` points to `vocabulary_size()` and you can find the same at below attached [source code](https://github.com/keras-team/keras/blob/424420588fc55cdb9f5040d975a31532f9a3e324/keras/layers/preprocessing/index_lookup.py#L416-L418).

```
def vocab_size(self):
    logging.warning("vocab_size is deprecated, please use vocabulary_size.")
    return self.vocabulary_size()

```
So in latest versions the method `vocab_size()` is deprecated and `vocabulary_size()` has to be used. For now it kept for may be backward compatibility but still internally its pointing to `vocabulary_size()` only.

I have also executed the tutorial in colab and works fine and attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/bbe3777d567e95a2c5daa6f4a7156ec7/copy-of-deep_neural_decision_forests.ipynb) for reference.

I hope this will clarify your query. Please check and come back if your issue is still not answered else feel free to close the issue.

Thnaks!
