### ISSUE TITLE
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'values' - I'm getting this error in the video_classification.py example

### ISSUE THREAD

**Issue by morganbelcher** [keras-team/keras-io#551]
I've been unable to resolve this error in line 185 of the video_classification.py example. I'm using tensorflow version 2.3.3.
Any help would be very much appreciated!

**Comment by SuryanarayanaY** [comment]
Hi @morganbelcher ,

Apologies for late response.We are in process of clearing backlogs. The reported error occurs when we call the method `values` on a TF Tensor. There is no such built-in method to call values directly from a tensor. Hence the error arising.

A simple code snippet is attached below to reproduce the error and as I mentioned this is expected behaviour if we call something like `my_tf_tensor.values()`. Please refer to the attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/b00ea5eb6e4e21a26ccfac6e0ffe0f8d/kefrasio_551.ipynb) also.

```
my_tf_tensor = tf.constant([[1.0, 2.0],[3.0, 4.0]])
my_tf_tensor.values()

#AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'values'
```

I have gone through the `video_classification.py` and I don't see values method being called on any Tensor. I can see only it was called on dataframe object which is fine. It seems the issue is resolved now already. Could you please cross check and confirm whether this is still an issue.

Thanks!
