### ISSUE TITLE
Data not found

### ISSUE THREAD

**Issue by HorusJiang** [keras-team/keras-io#616]
Hello, can anyone help with the data issue plz?
the URL in the code  [https://raw.githubusercontent.com/hfawaz/cd-diagram/master/FordA](https://raw.githubusercontent.com/hfawaz/cd-diagram/master/FordA)  don't work anymore.
Thank you!

**Comment by ymodak** [comment]
You may try https://github.com/hfawaz/cd-diagram/tree/master/FordA
Also refer [colab gist](https://colab.research.google.com/gist/ymodak/a7f348b12ac0424581c2b1e65269230d/untitled16.ipynb) to know more.

**Comment by SuryanarayanaY** [comment]
Hi @HorusJiang ,

The URL you mentioned is not valid. You should append FordA_TRAIN.tsv like https://raw.githubusercontent.com/hfawaz/cd-diagram/master/FordA/FordA_TRAIN.tsv which also mentioned in colab to get it worked. The colab also working fine as per attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/6888914089b6fc14f27273860a19ca52/kerasio_616-timeseries_classification_from_scratch.ipynb#scrollTo=sCoK4zr41xay).

Also you can refer to attached URL in above [comment](https://github.com/keras-team/keras-io/issues/616#issuecomment-917255705) if wants to check the contents.

I think the issue is resolved now and if so please feel free to close the issue.

Thanks!
