### ISSUE TITLE
model.save with swin_transformers.py

### ISSUE THREAD

**Issue by TLKline** [keras-team/keras-io#670]
Reporting issue with swin transformer example implementation. The model is not compatible with model.save. 

For example model.save generates:

```
line 349, in _fill_object_graph_proto
    child_proto.local_name = child.name
```

**Comment by SuryanarayanaY** [comment]
Hi @TLKline ,

Since the model is a custom model with subclassing type and its `__init__` method (constructor) has `non_python` arguments which needs implementation of `get_config()` and `from_config()` methods to make them serializable. You can refer this [resource](https://www.tensorflow.org/guide/keras/serialization_and_saving#custom_objects) for more details.

Since we have model architecture already available to us, we can simply use `save_weights` of the train model and using `load_weights` can load the weights again into the model.This is easy and recommended way for models with known architecture. The below additional code can solve your purpose. Please refer the attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/81ca3007bc10b6efe1950cbaba960c73/kerasio_670-swin_transformers.ipynb) also for same.

```
model.save_weights('my_model.weights.h5')
reloaded_model = tf.keras.models.clone_model(model)
reloaded_model.load_weights('my_model.weights.h5')
```
