### ISSUE TITLE
Trainable positional encoding: mlp_image_classification 

### ISSUE THREAD

**Issue by IbrahimSobh** [keras-team/keras-io#688]
Hello, 

Regarding the FNet code **mlp_image_classification.py**

I noticed that the trainable number of parameters (model.summary) is the same whether positional_encoding = True or False. 

I think something is wrong.

`def build_classifier(blocks, positional_encoding=False):`

Thank  you

**Comment by JanMarcelKezmann** [comment]
Hi @IbrahimSobh ,

at first the behavior of the positional encoding and with it the Embedding layer might seem irritating, since you would expect it to have *'input_dim'* **x** *'output_dim'* weights. This would hold if you would not call the layer while defining it, as can be seen within the **build_classifier()** function:

```python
        positions = tf.range(start=0, limit=num_patches, delta=1)
        position_embedding = layers.Embedding(
            input_dim=num_patches, output_dim=embedding_dim
        )(positions)
       x = x + position_embedding
```

Here you basically call the Embedding layer with *positions* before you compile it, which basically makes this layer an **EagerTensor**. Well this is than nothing other than an already (in that case uniformly) initialized weights vector, which is not trainable. This non trainable weight vector is than passed via an addition function to the model, so no weights are created there either.

This is the reason why the model has the same number of parameters whether *positional_encoding = True* or *False*, since you basically just add a fix vector to the model.

I hope that this short answer will help you.
