### ISSUE TITLE
Value error in semantic similarity with bert.

### ISSUE THREAD

**Issue by mirzayaser3** [keras-team/keras-io#711]
![image](https://user-images.githubusercontent.com/53065667/142210143-8160f5f8-212a-4dae-a765-ba89fa76a6c2.png)

**Comment by mirzayaser3** [comment]
Can someone please let me know how to resolve this value error.

**Comment by edgarhutauruk** [comment]
i got the same problem

**Comment by JanMarcelKezmann** [comment]
Hi I have taken a look at it and the issue lies in the value that is passed to the **predict()** function within the **check_similarity()** function.
In the example a list of length 1 is given to the model, which expects 3 values (i.e. numpy arrays). What you want is to pass the 3 elements of that list to the **predict()** function, since the elements of that list contain the input_ids, attention_masks and token_type_ids you want to pass to it.

So this is how a simple change could look like, change this:

```python
proba = model.predict(test_data)[0]
```

in **check_similarity(sentence1, sentence2)** to this:

```python
proba = model.predict(test_data[0])[0]
```

All in all the function should now look like that:

```python
def check_similarity(sentence1, sentence2):
    sentence_pairs = np.array([[str(sentence1), str(sentence2)]])
    test_data = BertSemanticDataGenerator(
        sentence_pairs, labels=None, batch_size=1, shuffle=False, include_targets=False,
    )

    proba = model.predict(test_data[0])[0]
    idx = np.argmax(proba)
    proba = f"{proba[idx]: .2f}%"
    pred = labels[idx]
    return pred, proba
```

**Comment by SuryanarayanaY** [comment]
Hi @mirzayaser3 ,

The proposed PR has been merged already. I have tested the tutorial with latest version and its working fine. Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/33b0d19f5bd81cca08282541b21a9f7b/711_semantic_similarity_with_bert.ipynb).

Please verify and feel free to close the issue. If still any issue there let us know. Thanks!
