### ISSUE TITLE
Grad-Cam Example

### ISSUE THREAD

**Issue by michael135** [keras-team/keras-io#784]
Hello,

It seems, that the **heatmap** is **shifted** in some cases.

Is it because of `keras.resize` interpolation limitations in `jet_heatmap = jet_heatmap.resize((img.shape[1], img.shape[0])) or there another **explanation** for this?

The image below is an example from official documentation: https://keras.io/examples/vision/grad_cam/

![image](https://user-images.githubusercontent.com/8559652/150680357-80a657fb-96b2-4d51-8bf6-68110cdf7033.png)

**Comment by SuryanarayanaY** [comment]
@michael135 ,

The reported behaviour os some shift in heatmap still observed. I can see similar heat map as earlier in the attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/b340c9455380cb736d67da1af03e9695/kerasio_784-grad_cam.ipynb). 

Needs to be checked whether this is expected.

**Comment by sampathweb** [comment]
@michael135 - 
The model used for this example is xception model, which is quite old backbone.  If you switch to a new model like ResNet or do fine-tuning the model might give localize better in gradcam results.  This notebook gives you an approach on how to reason about the predictions and confirm that model is learning the right things.

For example - If the dataset had images of person playing golf outside and is trained for golf activity, it might associate background field to Golf and not the actual activity.  GradCam can help understand what parts of the image resulted in the prediction to identify leakage, biases and shortcuts that network might be taking.  

Its not going to localize perfectly since we never told the neural network what to attend to like a bounding box, segmentation etc.  Closing this issue as no action needs to be taken.  Please let us know if you have followup questions.
