### ISSUE TITLE
'You must install pydot' in Structured data learning with Wide, Deep, and Cross networks

### ISSUE THREAD

**Issue by magicaltoast** [keras-team/keras-io#787]
Instead of visualization of the network the error stating ``You must install pydot`` is shown.
https://keras.io/examples/structured_data/wide_deep_cross_networks/

![Screenshot from 2022-01-28 19-29-24](https://user-images.githubusercontent.com/68669235/151601898-e57fce97-0f49-4b07-976b-85f97ae28d3d.png)

**Comment by SuryanarayanaY** [comment]
Hi @magicaltoast ,

I have executed the notebook in google colab and its working now. Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/6acddddff5c00184403f0b93af3c6988/kerasio_787-wide_deep_cross_networks.ipynb) here.

But in keras.io documentation the output cell still showing the reported error instead of the visual representation of network.
I think this needs to be fixed by rerunning the tutorial. I Will escalate to the TF docs team and try to fix it.

Thanks!
