### ISSUE TITLE
Suggestion that examples introduce their colab notebook with an interactive pre-trained example

### ISSUE THREAD

**Issue by gth001** [keras-team/keras-io#793]
My usual course of action, and I assume this is common, is to hit "Run All" on a new example, and come back to the tab an hour later after it finishes, before I begin reading. This allows me to try a few custom inputs, and see what the trained model does.

This default strikes me as a waste of audience time, and Google cloud TPU/GPU time. Also, some examples take so long to train that they time out the free Colab tier, so I never get a chance to see what they do.

My suggestion is, if possible, that examples begin with the pre-trained model, so the audience can immediately play with it and see what it does, and then begin the tutorial on training it yourself. In my view, this would make the Keras website more inviting to beginners. Thank you for considering.

**Comment by innat** [comment]
@gth001 cc. @ariG23498 
I can relate the request with this [code example](https://keras.io/examples/vision/patch_convnet/) and [web-api](https://huggingface.co/spaces/keras-io/patch-conv-net) to interact with it.

**Comment by merveenoyan** [comment]
If it's agreed, we can embed Gradio demos of those models inside the notebooks. (The API @ariG23498 made was made with Gradio)

I serialized most of the models in keras.io and I'm currently hosting them [here](https://huggingface.co/keras-io) so that people can pull and try for themselves, @ariG23498 and I are making demos based on them as well.

The last [QA example we contributed to keras.io](https://keras.io/examples/nlp/question_answering/) is also hosted [here](https://huggingface.co/keras-io/transformers-qa) and demonstrated [here](https://huggingface.co/spaces/keras-io/keras-qa). It's very convenient tbh.

**Comment by innat** [comment]
https://twitter.com/abidlabs/status/1496558866837954566?s=20&t=fW0rezLJAVg1usQITecllw

**Comment by pcoet** [comment]
It looks like we have a path forward for this issue: Add Hugging Face spaces to tutorials. Thanks for the suggestion, @gth001!
