### ISSUE TITLE
tfds split uses wrong format, yields error

### ISSUE THREAD

**Issue by EngrStudent** [keras-team/keras-io#800]
This:    

```
train_ds, validation_ds, test_ds = tfds.load(
    "cats_vs_dogs",
    # Reserve 10% for validation and 10% for test
    split=["train[:40%]", "train[40%:50%]", "train[50%:60%]"],
    as_supervised=True,  # Include labels
)
```

yields this:    
`KeyError: "Invalid split train[:40%]. Available splits are: ['train']"`

If you look here:
https://stackoverflow.com/questions/59959438/keyerror-invalid-split-train80-available-splits-are-train

You can see that it should look like this:    
`split=[
   tfds.Split.TRAIN.subsplit(tfds.percent[:80]),
   tfds.Split.TRAIN.subsplit(tfds.percent[80:90]),
   tfds.Split.TRAIN.subsplit(tfds.percent[90:])
],`

**Comment by SuryanarayanaY** [comment]
Hi @EngrStudent ,

This issue is not there now. I have tested the tutorial and its working fine with split happening as well as model also got trained.

I have also tested the code for 3 splits explicitly and it's also success.

```
train_ds, validation_ds, test_ds = tfds.load(
    "cats_vs_dogs",
    # Reserve 10% for validation and 10% for test
    split=["train[:40%]", "train[40%:50%]", "train[50%:60%]"],
    as_supervised=True,  # Include labels
)
```
Please refer the attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/6b40a6e652abd65280a6af7e8fe13b78/kerasio_800-of-learnable_resizer.ipynb) for same.

Please check and feel free to close if resolved else come back if any issues. Thanks!
