### ISSUE TITLE
How to save model after training?

### ISSUE THREAD

**Issue by smith-co** [keras-team/keras-io#926]
I am following the [Image similarity estimation using a Siamese Network with a triplet loss](https://github.com/keras-team/keras-io/blob/master/examples/vision/siamese_network.py#L340) example.

I see the model is trained [here](https://github.com/keras-team/keras-io/blob/master/examples/vision/siamese_network.py#L346).

`siamese_model.fit(train_dataset, epochs=10, validation_data=val_dataset)
`

But the model is not saved after training. How to save the model after training so that we don't need to re-train the model from scratch during evaluation?

Also I see the example mentions `Writing a training loop from scratch`. I am not sure what's the purpose of that. Can anyone please explain?

**Comment by nashid** [comment]
You can try with `siamese_model.save`.

**Comment by nashid** [comment]
Hmm, once I try this I get:

```
ValueError: Model <siamese_model.SiameseModel object at 0x17e85a280> cannot be saved either because the input shape is not available or because the forward pass of the model is not defined.To define a forward pass, please override `Model.call()`. To specify an input shape, either call `build(input_shape)` directly, or call the model on actual data using `Model()`, `Model.fit()`, or `Model.predict()`. If you have a custom training step, please make sure to invoke the forward pass in train step through `Model.__call__`, i.e. `model(inputs)`, as opposed to `model.call()`.
```
@svpino @ hazemessamm any idea?

**Comment by hazemessamm** [comment]
I tried ```tf.keras.models.save_model(siamese_network, '/content/saved_model')``` and it worked, I also tried to reload the saved model and it worked using ```loaded_siamese_model = tf.keras.models.load_model('/content/saved_model')```. Let me know if that did not help you.

**Comment by smith-co** [comment]
@hazemessamm I don't quite follow from your example how to apply your model during inference. Lets say I trained a model in the step `siamese_model.fit(..)`

Now how to apply this model to a a new set of images? Lets say I just have `image1.jpg` and `image2.jpg` and I want to know whether they are similar or not.

How could I do that?

**Comment by smith-co** [comment]
@hazemessamm Also the positive and negative similarity is so so close i.e. `0.994` vs `0.991`

```
Positive similarity: 0.9940324
Negative similarity 0.9918252
```

Why is that? Can you provide an insight?

**Comment by nashid** [comment]
> @hazemessamm I don't quite follow from your example how to apply your model during inference. Lets say I trained a model in the step `siamese_model.fit(..)`
> 
> Now how to apply this model to a a new set of images? Lets say I just have `image1.jpg` and `image2.jpg` and I want to know whether they are similar i.e. `siamese_model.predict(..)`.
> 
> How could I do that? Any help is welcome.

@smith-co you can compute embedding with `embedding(resnet.preprocess_input(your_image))` and then perform cosine similarity i.e. `cosine_similarity(`your_image_1`,  `your_image_2`)`.

But yeah its a good question why the similarity between positive and negative example is so close. I suppose @hazemessamm can give better feedback regarding that as he is the author of this code.

**Comment by hazemessamm** [comment]
> @hazemessamm this works for me. 
> 
> 
> 
> A quick question abut the dataset. I have to train with a new dataset. For this I am building anchor, positive, negative pairs following your example.
> 
> 
> 
> Looks like I have to create the following structure for image pairs:
> 
> 
> 
> `left`   folder:  anchor images
> 
> `right` folder:  positive images
> 
> 
> 
> For example, if `left/00001.png` is the anchor image, then `right/00001.png` is the positive pair. Is this understanding correct?
> 
> 
> 
> 

Yes, correct.

**Comment by smith-co** [comment]
> I think the similarity issue was most probably due to overfitting, in the example we used pre-trained ResNet50 and fine tuned it and added after it 3 Dense layers while as I remember the dataset size was not that big (I don't remember the exact size) and also there are some best practices that were not applied in the example like data augmentation, dropout and adding more dissimilar pairs than similar pairs. It also might be better if you disable the fine tuning part or reduced number of layers.

Thanks for your reply @hazemessamm. For my case, I am trying to run on a completely different type of dataset. So I suppose during fine-tuning, I should try:

1.  data augmentation
2.  dropout
3.  adding more dissimilar pairs than similar pairs.
4. Reduce number of layers

I have a few questions:

1. For step 3 (`adding more dissimilar pairs than similar pairs`), I am confused as we always have same number of positive and negative image. Isn't it? 

2. Is there a way to get the `threshold` for similarity matching programatically? 
```
Positive similarity: 0.9940324
Negative similarity 0.9918252
```
What should be the `threshold` for similarity `0.991`? Can we do it programatically?

**Comment by hazemessamm** [comment]
> > I think the similarity issue was most probably due to overfitting, in the example we used pre-trained ResNet50 and fine tuned it and added after it 3 Dense layers while as I remember the dataset size was not that big (I don't remember the exact size) and also there are some best practices that were not applied in the example like data augmentation, dropout and adding more dissimilar pairs than similar pairs. It also might be better if you disable the fine tuning part or reduced number of layers.
> 
> Thanks for your reply @hazemessamm. For my case, I am trying to run on a completely different type of dataset. So I suppose during fine-tuning, I should try:
> 
> 1. data augmentation
> 2. dropout
> 3. adding more dissimilar pairs than similar pairs.
> 4. Reduce number of layers
> 
> I have a few questions:
> 
> 1. For step 3 (`adding more dissimilar pairs than similar pairs`), I am confused as we always have same number of positive and negative image. Isn't it?
> 2. Is there a way to get the `threshold` for similarity matching programatically?
> 
> ```
> Positive similarity: 0.9940324
> Negative similarity 0.9918252
> ```
> 
> What should be the `threshold` for similarity `0.991`? Can we do it programatically?

Regarding the first question, in the example you will find that the negative dataset is fixed, which means that it concatenates the postive and anchor datasets then shuffles them then finally it used the shuffled dataset as the negative dataset, I think the better approach is instead of fixing the negative dataset, it should load a random negative example with every positive and anchor example, doing it this way will result in better performance because the network will see different negative examples with the same positive and anchor examples. I am sorry if I could not make it clear previously.

Regarding the threshold, I think you can plot a histogram after training which plots many different prediction results (similarity scores) between two different and similar images and by plotting it you will get better approximation on what threshold you should set (I did not try this before, but I think it's a good way to get better approx.).

**Comment by hazemessamm** [comment]
Regarding my last answer when I said that "negative dataset" is fixed, I misunderstood the negative dataset part and I thought that it is fixed but I tried it now and it is not, sorry for the confusion.

**Comment by hazemessamm** [comment]
I found a bug in the `SiameseModel`, in the `_compute_loss` function, it should accept `data` and `training` where `training` is `bool`, because in this function we should pass `self.siamese_network(data, training=True)` while training and  `self.siamese_network(data, training=False)` while evaluation, so we should pass `training=True` to `_compute_loss` in `train_step` and  `training=False` in `test_step`,  when I changed it it gave me much better results and my conclusion is that it was updating the weights while `training=False` which is wrong because it changes the behaviour of some layers.

The results after the changes:
Example 1:
`Positive similarity: 0.7165001
Negative similarity 0.29234624`

Example 2:
`Positive similarity: 0.658884
Negative similarity 0.49629968`

Example 3:
`Positive similarity: 0.10523224
Negative similarity 0.028869186`

Example 4:
Positive similarity: 0.36360863
Negative similarity 0.097729616

I expect that it needs more training and more examples to perform better but these scores are much more realistic.

Also another bug I found in the inference part, previously we were passing to the cosine similarity a batch of examples which I think is wrong, the reason of why I think it's wrong is that we were passing an input with batch size 32 and it still outputs a single cosine similarity score while I think it should output 32 cosine similarity scores for each example in the batch:

I modified it to output a similarity score for single example.

`cosine_similarity = metrics.CosineSimilarity()

example_num = 0

positive_similarity = cosine_similarity(anchor_embedding[None, example_num, :], positive_embedding[None, example_num, :])
print("Positive similarity:", positive_similarity.numpy())

negative_similarity = cosine_similarity(anchor_embedding[None, example_num, :], negative_embedding[None, example_num, :])
print("Negative similarity", negative_similarity.numpy())`

**Comment by hazemessamm** [comment]
That's how I modified it.

```def _compute_loss(self, data, training=True):
        # The output of the network is a tuple containing the distances
        # between the anchor and the positive example, and the anchor and
        # the negative example.
        ap_distance, an_distance = self.siamese_network(data, training=training)

        # Computing the Triplet Loss by subtracting both distances and
        # making sure we don't get a negative value.
        loss = ap_distance - an_distance
        loss = tf.maximum(loss + self.margin, 0.0)
        return loss```

**Comment by hazemessamm** [comment]
> @hazemessamm the results looks more promising this way. I presume you would submit a pull request to update the example?

Yes I will, I already added the latest changes, I will re-train the model and submit a pull request soon.

**Comment by smith-co** [comment]
> Also another bug I found in the inference part, previously we were passing to the cosine similarity a batch of examples which I think is wrong, the reason of why I think it's wrong is that we were passing an input with batch size 32 and it still outputs a single cosine similarity score while I think it should output 32 cosine similarity scores for each example in the batch:
> 
> I modified it to output a similarity score for single example.
> 
> ```
> cosine_similarity = metrics.CosineSimilarity()
> 
> example_num = 0
> 
> positive_similarity = cosine_similarity(anchor_embedding[None, example_num, :], positive_embedding[None, example_num, :])
> print("Positive similarity:", positive_similarity.numpy())
> 
> negative_similarity = cosine_similarity(anchor_embedding[None, example_num, :], negative_embedding[None, example_num, :])
> print("Negative similarity", negative_similarity.numpy())
> ```

@hazemessamm I have not followed what you referred to about `batch size 32` during inference.  

My understanding is you took one sample here: `sample = next(iter(train_dataset))`

**Comment by smith-co** [comment]
@hazemessamm I see you are using `batch size` and that's what you were referring. 

By the way, I think it would be better to have a dataset split of `80/10/10` for `train/validation/test`.

Currently inference is executed on training which is not meaningful. So in my humble opinion it would be awesome to run the model during inference on the test dataset after doing the 80/10/10 split. 

And thanks again for your fantastic work 👍

**Comment by smith-co** [comment]
@hazemessamm this makes complete sense. Thanks @hazemessamm 🙏 

By the way, after running your code, it kept me thinking how `contrastive learning` would work in comparison to `triplet loss`. How would the results vary with contrastive learning?  I suppose that would be super interesting example.

If we want to adapt your example for `contrastive learning` I suppose we need to change the following:

- DistanceLayer
- _compute_loss 

Any help is appreciated.
